campus_map = [{'name': 'Reimar Lüst Hall (RLH)', 'direction': 'north', 'category': 'Administration', 'aliases': ['rlh', 'reimar lust hall', 'reimar lüst hall']},
              {'name': 'Reception', 'direction': 'west', 'category': 'Administration', 'aliases': ['reception', 'admin entrance', 'visitor desk']},
              {'name': 'Receiving', 'direction': 'west', 'category': 'Administration', 'aliases': ['receiving', 'delivery area']},
              {'name': 'Research 1', 'direction': 'center', 'category': 'Research & Teaching', 'aliases': ['research 1', 'r1']},
              {'name': 'Research 2', 'direction': 'center', 'category': 'Research & Teaching', 'aliases': ['research 2', 'r2']},
              {'name': 'Research 3', 'direction': 'center', 'category': 'Research & Teaching', 'aliases': ['research 3', 'r3']},
              {'name': 'Research 4', 'direction': 'center', 'category': 'Research & Teaching', 'aliases': ['research 4', 'r4']},
              {'name': 'Robotics Lab', 'direction': 'west', 'category': 'Research & Teaching', 'aliases': ['robotics lab', 'robotics']},
              {'name': 'Ocean Lab', 'direction': 'center', 'category': 'Research & Teaching', 'aliases': ['ocean lab', 'marine lab']},
              {'name': 'Lab 2', 'direction': 'south', 'category': 'Research & Teaching', 'aliases': ['lab 2', 'teaching lab 2']},
              {'name': 'Lab 3', 'direction': 'west', 'category': 'Research & Teaching', 'aliases': ['lab 3', 'teaching lab 3']},
              {'name': 'EON Lab', 'direction': 'center', 'category': 'Research & Teaching', 'aliases': ['eon lab', 'eon']},
              {'name': 'Campus Center / IRC', 'direction': 'north', 'category': 'Public Space', 'aliases': ['irc', 'library', 'information resource center', 'campus center']},
              {'name': 'University Club', 'direction': 'north', 'category': 'Public Space', 'aliases': ['university club', 'club']},
              {'name': 'The Other Side', 'direction': 'north', 'category': 'Public Space', 'aliases': ['the other side', 'tos']},
              {'name': 'Music Lab, Theater Space, Cinema', 'direction': 'north', 'category': 'Public Space', 'aliases': ['music lab', 'theater', 'cinema', 'arts center']},
              {'name': 'Playing Field', 'direction': 'southeast', 'category': 'Public Space', 'aliases': ['playing field', 'football field', 'sports field']},
              {'name': 'Kids at Jacobs', 'direction': 'south', 'category': 'Public Space', 'aliases': ['kids at jacobs', 'daycare']},
              {'name': 'Sports & Convention Center (SCC)', 'direction': 'east', 'category': 'Public Space', 'aliases': ['scc', 'gym', 'sports center', 'convention center']},
              {'name': 'Student Activity Center (SAC)', 'direction': 'east', 'category': 'Public Space', 'aliases': ['sac', 'student activity center', 'activity center']},
              {'name': 'Campus Green', 'direction': 'center', 'category': 'Public Space', 'aliases': ['campus green', 'green', 'lawn']},
              {'name': 'Main Gate', 'direction': 'west', 'category': 'Public Space', 'aliases': ['main gate', 'entrance', 'gate', 'porters']},
              {'name': 'Krupp College', 'direction': 'northeast', 'category': 'Residence', 'aliases': ['krupp', 'krupp college', 'krupp dorms']},
              {'name': 'Mercator College', 'direction': 'east', 'category': 'Residence', 'aliases': ['mercator', 'mercator college', 'mercator dorms']},
              {'name': 'College 3', 'direction': 'east', 'category': 'Residence', 'aliases': ['college 3', 'c3', 'college three']},
              {'name': 'Nordmetall College', 'direction': 'north', 'category': 'Residence', 'aliases': ['nordmetall', 'nordmetall college', 'north dorms']},
              {'name': 'West Hall', 'direction': 'northeast', 'category': 'Residence', 'aliases': ['west hall', 'wh', 'wh1', 'wh2', 'wh3', 'wh4', 'wh5', 'wh6', 'wh7', 'wh8', 'wh9', 'wh10']},
              {'name': 'South Hall', 'direction': 'northeast', 'category': 'Residence', 'aliases': ['south hall', 'sh', 'sh1', 'sh2', 'sh3', 'sh4', 'sh5', 'sh6', 'sh7', 'sh8', 'sh9', 'sh10']},
              {'name': 'East Hall', 'direction': 'east', 'category': 'Residence', 'aliases': ['east hall', 'eh', 'eh1', 'eh2', 'eh3', 'eh4', 'eh5', 'eh6', 'eh7', 'eh8', 'eh9', 'eh10']}
              ]