services:
  chatbot:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      MISTRAL_API_KEY:            ${MISTRAL_API_KEY}
      HF_TOKEN:                   ${HF_TOKEN}
      TELEGRAM_TOKEN:             ${TELEGRAM_TOKEN}
      SUPABASE_URL:               ${SUPABASE_URL}
      SUPABASE_SERVICE_ROLE_KEY:  ${SUPABASE_SERVICE_ROLE_KEY}
    volumes:
        - ./:/app
    restart: unless-stopped
