services:
  chatbot:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      MISTRAL_API_KEY:            ${MISTRAL_API_KEY}
      HF_TOKEN:                   ${HF_TOKEN}
      TELEGRAM_TOKEN:             ${TELEGRAM_TOKEN}
      SUPABASE_URL:               ${SUPABASE_URL}
      SUPABASE_SERVICE_ROLE_KEY:  ${SUPABASE_SERVICE_ROLE_KEY}
    volumes:
        - ./:/app
    command: ["uv", "run", "python3", "src/uni_ai_chatbot/main.py"]